app:
  source_folder: /downloads
  target_folder: /media
  min_duration: 600
  scan_interval: 60
  video_extensions:
    - .mkv
    - .mp4
    - .avi
    - .ts
    - .mov
    - .wmv
    - .flv
  debug: false

database:
  uri: sqlite:////data/hardlinks.db
