version: '3.8'

services:
  app:
    image: ghcr.io/canxi/seedlink:latest
    container_name: seedlink
    ports:
      - "5000:5000"
    volumes:
      - ./.env.docker:/app/config/.env
      - ./data:/app/data
      - /downloads:/downloads:ro
      - /media:/media
    environment:
      - TZ=Asia/Shanghai
      - DATABASE_URI=sqlite:////app/data/hardlinks.db
    restart: unless-stopped
