version: '3.8'

services:
  app:
    image: ghcr.io/canxi/seedlink:latest
    container_name: seedlink
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - /downloads:/downloads:ro
      - /media:/media
    environment:
      - CONFIG_PATH=/app/config/config.json
      - TZ=Asia/Shanghai
    restart: unless-stopped
